name: Laravel

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: ovz1.j1121565.m2oon.vps.myjino.ru
        password: ${{ secrets.SSH_PASSWORD }}
        port: 49346
        script: 'cd /var/www/requests_backend && ./server_deploy.sh'
